package ru.home.MyHHBot.botApi.entity;

public enum BotState {
    GREETING,
    CURRENT_OPTIONS,
    FIND_JOB,
    GET_VACANCIES,
    ASK_OPTIONS,
    ASK_COUNTRY,
    ASK_REGION,
    ASK_CITY,
    ASK_SPECIALIZATION,
    ASK_SPECIALIZATION_SUBLIST,
    ASK_DISPLAY_WAGES,
    ASK_MIN_SALARY,
    ASK_JOB_DESCRIPTION,
    FILLING_PROFILE
}
